import{i as c,a as p,S as h}from"./assets/vendor-ba070a68.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))d(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&d(i)}).observe(document,{childList:!0,subtree:!0});function e(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function d(t){if(t.ep)return;t.ep=!0;const o=e(t);fetch(t.href,o)}})();const y=document.getElementById("search-form"),u=document.querySelector(".gallery");let a="",n=1;const l=40,g="44418416-01658c71a65aed4380a3ece44",b="https://pixabay.com/api/",f=async(s,r)=>{try{return(await p.get(b,{params:{key:g,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:l}})).data}catch(e){console.error(e)}},m=s=>{const r=s.map(e=>`
        <a href="${e.largeImageURL}" class="photo-card">
            <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
            <div class="info">
                <p class="info-item"><b>Likes:</b> ${e.likes}</p>
                <p class="info-item"><b>Views:</b> ${e.views}</p>
                <p class="info-item"><b>Comments:</b> ${e.comments}</p>
                <p class="info-item"><b>Downloads:</b> ${e.downloads}</p>
            </div>
        </a>
    `).join("");u.insertAdjacentHTML("beforeend",r),new h(".gallery a",{captionDelay:250}).refresh()},w=()=>{u.innerHTML=""},L=()=>{const{height:s}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:s*2,behavior:"smooth"})},v=new IntersectionObserver(async(s,r)=>{if(s[0].isIntersecting){n+=1;const e=await f(a,n);m(e.hits),L(),n*l>=e.totalHits&&(r.disconnect(),c.info({title:"Info",message:"We're sorry, but you've reached the end of search results."}))}},{rootMargin:"200px"}),S=async s=>{if(s.preventDefault(),a=s.currentTarget.elements.searchQuery.value.trim(),!a)return;n=1,w();const r=await f(a,n);if(r.hits.length===0){c.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again."});return}m(r.hits),c.success({title:"Success",message:`Hooray! We found ${r.totalHits} images.`}),r.hits.length===l&&v.observe(document.querySelector(".gallery").lastElementChild)};y.addEventListener("submit",S);
//# sourceMappingURL=commonHelpers.js.map
